### ISSUE TITLE
发送中文文件名失败

### ISSUE THREAD

**Issue by halodongt** [yuxiaoli/wcf-http#1]
WeChatFerry v39.2.4 貌似会有中文文件名发送失败的bug，期盼大佬更新v39.3.3版本，万分感谢。

![企业微信截图_1732181336483](https://github.com/user-attachments/assets/44a59c95-a31b-4c7b-b0b6-7ec9a5f1b01f)

![企业微信截图_17321813639188](https://github.com/user-attachments/assets/68414983-c80b-40eb-bee1-cb7b73e5fbe9)

![image](https://github.com/user-attachments/assets/aadd0e47-bacb-4e43-b157-36bb6eac784b)

**Comment by yuxiaoli** [comment]
中文路径是一个系统设置问题，可以参考一下这个[issue](https://github.com/lich0821/WeChatFerry/issues/140)

**Comment by halodongt** [comment]
感谢大佬解答，
因为我是在windows server部署，区域设置里没有更换编码的选项，我手动把wcferry升级39.3.3.0后解决了这个问题，但这个版本发送文件api存在微信崩溃的问题，使用发送图片api是正常的（发送文件也正常），期盼大佬关注。非常感谢。

**Comment by yuxiaoli** [comment]
我更新了[3.9.11.25](https://github.com/yuxiaoli/wcf-http/tree/3.9.11.25)，你可以试试。我的项目是基于3.9.10.27的，所以默认分支还是3.9.10.27

**Comment by halodongt** [comment]
非常感谢
