### ISSUE TITLE
发送卡片消息提示错误

### ISSUE THREAD

**Issue by Ai-Yolo** [yuxiaoli/wcf-http#2]
消息成功发送了，但是http接口返回失败，这里的原因和日志都找不到...

请求/rich-text ：
{
  "name": "碲矿",
  "account": "gh_75dea2d6c71f",
  "title": "【FAQ】WeChatFerry 机器人常见问题 v39.0.10",
  "digest": "先看再问，少走弯路。",
  "url": "http://mp.weixin.qq.com/s?__biz=MzI0MjI1OTk0OQ==&mid=2247487601&idx=1&sn=1bf7a0d1c659f8bc78a00cba18d7b204",
  "thumburl": "https://mmbiz.qpic.cn/mmbiz_jpg/XaSOeHibHicMGIiaZsBeYYjcuS2KfBGXfm8ibb9QrKJqk0H0W3JHia9icVica9nlWMiaD0xWmA0pKHpMOWbeBCJaAQc2IQ/0?wx_fmt=jpeg",
  "receiver": "filehelper"
}

响应：
{
  "status": 1,
  "message": "失败，原因见日志"
}

**Comment by yuxiaoli** [comment]
用的是哪个分支版本？

**Comment by Ai-Yolo** [comment]
v39.2.4.1.15 

https://github.com/yuxiaoli/wcf-http/releases/tag/v39.2.4.1.15

**Comment by yuxiaoli** [comment]
v39.2.4.1.15虽然返回失败，但信息应该是发出去了。具体原因我也没有仔细看

**Comment by Ai-Yolo** [comment]
应该是原作者的代码问题（我用原作者开发的也有类似的问题，最新版是直接发不出去卡片信息了...感谢回复，不影响实际使用
